Table アカウント情報 {
    アカウントID    int [pk]
    メールアドレス  varchar [unique]
    パスワード      varchar 
    利用者区分      char 
    作成日時        datetime 
    作成者          int [note: 'アカウント情報.アカウントIDを参照']
    更新日時        datetime
    更新者          int [note: 'アカウント情報.アカウントIDを参照']
}

Table 基本情報 {
    アカウントID      int [pk,note: 'アカウント情報.アカウントIDを参照']          
    氏名_姓           varchar 
    氏名_名           varchar 
    電話番号          varchar 
    作成日時          datetime
    作成者            int     [note: 'アカウント情報.アカウントIDを参照']   
    更新日時          datetime
    更新者            int     [note: 'アカウント情報.アカウントIDを参照']   
}
Ref: 基本情報.アカウントID - アカウント情報.アカウントID

Table 生徒情報 {
    アカウントID      int [pk,note: 'アカウント情報.アカウントIDを参照']            
    講師アカウントID  int     
    受講コース        char    
    作成日時          datetime
    作成者            int     [note: 'アカウント情報.アカウントIDを参照'] 
    更新日時          datetime
    更新者            int     [note: 'アカウント情報.アカウントIDを参照']    
}
Ref: 生徒情報.アカウントID - アカウント情報.アカウントID
Ref: 生徒情報.アカウントID - 基本情報.アカウントID
Ref: 生徒情報.講師アカウントID  > 講師情報.アカウントID 
Ref: 生徒情報.受講コース >  講師情報.講師担当コース 

Table 講師情報 {
    アカウントID      int [pk,note: 'アカウント情報.アカウントIDを参照']       
    講師担当コース     char [pk]    
    作成日時          datetime
    作成者            int     [note: 'アカウント情報.アカウントIDを参照']   
    更新日時          datetime
    更新者            int     [note: 'アカウント情報.アカウントIDを参照']   
}
Ref: 講師情報.アカウントID - アカウント情報.アカウントID
Ref: 講師情報.アカウントID - 基本情報.アカウントID


Table レッスンスケジュール {
    レッスン枠ID      int [pk] 
    講師アカウントID  int [note: 'アカウント情報.アカウントIDを参照']   
    コース            char  
    開始日時          datetime 
    予約フラグ        boolean
    作成日時          datetime 
    作成者            int [note: 'アカウント情報.アカウントIDを参照']
    更新日時          datetime 
    更新者            int     [note: 'アカウント情報.アカウントIDを参照']  
}
Ref: レッスンスケジュール.講師アカウントID >  講師情報.アカウントID
Ref: レッスンスケジュール.コース > 講師情報.講師担当コース

Table レッスン予約 {
レッスン枠ID     int [pk,note: 'レッスンスケジュール情報.レッスン枠IDを参照'] 
生徒アカウントID  int [note: 'アカウント情報.アカウントIDを参照']
作成日時          datetime 
作成者            int     [note: 'アカウント情報.アカウントIDを参照']
更新日時          datetime 
更新者            int     [note: 'アカウント情報.アカウントIDを参照']  
}
Ref: レッスン予約.レッスン枠ID -  レッスンスケジュール.レッスン枠ID
Ref: レッスン予約.生徒アカウントID >  生徒情報.アカウントID